# Generated by Django 5.2.3 on 2025-07-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='fieldName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tree',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trees/images/'),
        ),
        migrations.AddField(
            model_name='tree',
            name='lineNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tree',
            name='plantId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tree',
            name='plantNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='desc',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
