# Generated by Django 5.2.3 on 2025-07-02 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_tree_fieldname_tree_image_tree_linenumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='image',
            new_name='imageUrl',
        ),
    ]
