# Generated by Django 5.2.3 on 2025-07-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0003_rename_image_tree_imageurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='desc',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='type',
        ),
        migrations.AddField(
            model_name='tree',
            name='plantName',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='tree',
            name='plantType',
            field=models.CharField(choices=[('Wild', 'Wild'), ('Medicinal', 'Medicinal'), ('Fruit', 'Fruit')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='tree',
            name='fieldName',
            field=models.CharField(choices=[('F1', 'F1'), ('F2', 'F2'), ('F3', 'F3')], default='F1', max_length=20),
        ),
        migrations.AlterField(
            model_name='tree',
            name='lineNumber',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='tree',
            name='plantId',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='plantNumber',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
